backend:
  name: git-gateway
  branch: master

#publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images"

collections:
  - name: "profile"
    label: "Profile"
    folder: "content/profiles"
    create: true
    slug: {{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Type", name: "type", widget: "string", default: "profile"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Eloquent JavaScript Exercise"
    label: "eloquent"
    folder: "content/eloquent"
    create: true
    slug: {{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Your Name Here!"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Type", name: "type", widget: "string", default: "article"}
      - {label: "Body", name: "body", widget: "markdown"}


